name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run linters
        run: |
          make lint
      - name: Run tests
        timeout-minutes: 5
        run: |
          make test
      - name: Build
        run: |
          poetry build
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: python-package
          path: dist
