name: Canary build
# Upgrade and build periodically to check compatibility with the latest
# versions of dependencies.

on:
  schedule:
  - cron: "43 10 * * 4"

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install locked dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Scan for security issues
        timeout-minutes: 5
        run: |
          make scan

  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install locked dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Upgrade dependencies
        run: |
          poetry update
      - name: Build with latest dependencies
        timeout-minutes: 5
        run: |
          make all
