name: Canary build

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Upgrade dependencies
        run: |
          poetry update
      - name: Build
        timeout-minutes: 5
        run: |
          make
