name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Check that version matches tag
      run: |
        [[ "sparcli ${GITHUB_REF#refs/heads/}" == $(poetry version) ]]
    - name: Run tests
      timeout-minutes: 5
      run: |
        make test
    - name: Run security scanners
      timeout-minutes: 5
      run: |
        make scan
    - name: Build
      run: |
        make build
    - name: Publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: |
        make publish
